### ISSUE TITLE
Missing CHANGELOG.md

### ISSUE THREAD

**Issue by vincentsarago** [kylebarron/suncalc-py#1]
```bash
pip --no-cache-dir install suncalc
Collecting suncalc
  Downloading suncalc-0.1.0.tar.gz (9.7 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/vincentsarago/Workspace/venv/py37/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/s1/0w9w64dd7gl6jvh5j9b_dp_80000gn/T/pip-install-wag1jlc3/suncalc/setup.py'"'"'; __file__='"'"'/private/var/folders/s1/0w9w64dd7gl6jvh5j9b_dp_80000gn/T/pip-install-wag1jlc3/suncalc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/s1/0w9w64dd7gl6jvh5j9b_dp_80000gn/T/pip-pip-egg-info-bpln2bvk
         cwd: /private/var/folders/s1/0w9w64dd7gl6jvh5j9b_dp_80000gn/T/pip-install-wag1jlc3/suncalc/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/s1/0w9w64dd7gl6jvh5j9b_dp_80000gn/T/pip-install-wag1jlc3/suncalc/setup.py", line 9, in <module>
        with open('CHANGELOG.md') as history_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'CHANGELOG.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Confirmed when running `python setup.py sdist`, it doesn't ship the CHANGELOG.md

```bash
python setup.py sdist    
running sdist
running egg_info
creating suncalc.egg-info
writing suncalc.egg-info/PKG-INFO
writing dependency_links to suncalc.egg-info/dependency_links.txt
writing requirements to suncalc.egg-info/requires.txt
writing top-level names to suncalc.egg-info/top_level.txt
writing manifest file 'suncalc.egg-info/SOURCES.txt'
reading manifest file 'suncalc.egg-info/SOURCES.txt'
writing manifest file 'suncalc.egg-info/SOURCES.txt'
running check
creating suncalc-0.1.0
creating suncalc-0.1.0/suncalc
creating suncalc-0.1.0/suncalc.egg-info
copying files to suncalc-0.1.0...
copying README.md -> suncalc-0.1.0
copying setup.cfg -> suncalc-0.1.0
copying setup.py -> suncalc-0.1.0
copying suncalc/__init__.py -> suncalc-0.1.0/suncalc
copying suncalc/suncalc.py -> suncalc-0.1.0/suncalc
copying suncalc.egg-info/PKG-INFO -> suncalc-0.1.0/suncalc.egg-info
copying suncalc.egg-info/SOURCES.txt -> suncalc-0.1.0/suncalc.egg-info
copying suncalc.egg-info/dependency_links.txt -> suncalc-0.1.0/suncalc.egg-info
copying suncalc.egg-info/not-zip-safe -> suncalc-0.1.0/suncalc.egg-info
copying suncalc.egg-info/requires.txt -> suncalc-0.1.0/suncalc.egg-info
copying suncalc.egg-info/top_level.txt -> suncalc-0.1.0/suncalc.egg-info
Writing suncalc-0.1.0/setup.cfg
creating dist
Creating tar archive
removing 'suncalc-0.1.0' (and everything under it)
```

**Comment by kylebarron** [comment]
🤦‍♂️
