### ISSUE TITLE
Receiving a "numpy.float64 object is not iterable" exception in from_julian when calling get_times() near the summer solstice

### ISSUE THREAD

**Issue by mrputter** [kylebarron/suncalc-py#4]
Trying to use the package to calculate various times throughout the year for Calgary Canada (51.0447 lat, -114.0719 long).

`get_times()` works fine for most of the year, but fails when within ~ 26 days of the summer solstice (specifically ~2AM May 25 through 2AM July 18, 2020; the range is slightly different in other years).

"Failure" manifests as a `'numpy.float64' object is not iterable` TypeError in `from_julian()` (line 111 of `suncalc.py`).

Trace/error message/steps to reproduce follow:

```
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from suncalc import get_times
>>> from datetime import datetime
>>> get_times(datetime(2020,5,26,0,0,0), -114.0719, 51.0447)
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\suncalc\suncalc.py", line 111, in from_julian
    return np.array([datetime.utcfromtimestamp(x / 1000) for x in ms_date])
TypeError: 'numpy.float64' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python38\lib\site-packages\suncalc\suncalc.py", line 291, in get_times
    result[time[1]] = from_julian(Jrise[idx])
  File "C:\Program Files\Python38\lib\site-packages\suncalc\suncalc.py", line 114, in from_julian
    return datetime.utcfromtimestamp(ms_date / 1000)
ValueError: Invalid value NaN (not a number)
>>>
```

Suncalc 0.1.1 (freshly installed):
```
C:\>pip list | findstr "suncalc numpy"
numpy                     1.19.4
suncalc                   0.1.1
```

**Comment by kylebarron** [comment]
It's weird that that errors for you, it doesn't for me with numpy 1.19.1, though I do get a runtime warning:
```py
>>> from suncalc import get_times
>>> from datetime import datetime
>>> get_times(datetime(2020,5,26,0,0,0), -114.0719, 51.0447)
```
```
/Users/kyle/github/mapping/suncalc-py/suncalc/suncalc.py:199: RuntimeWarning: invalid value encountered in arccos
  return acos((sin(h) - sin(phi) * sin(d)) / (cos(phi) * cos(d)))

{'solar_noon': Timestamp('2020-05-25 19:34:45.199338135'),
 'nadir': Timestamp('2020-05-25 07:34:45.199338135'),
 'sunrise': Timestamp('2020-05-25 11:34:21.637714600'),
 'sunset': Timestamp('2020-05-26 03:35:08.760961914'),
 'sunrise_end': Timestamp('2020-05-25 11:38:32.347278076'),
 'sunset_start': Timestamp('2020-05-26 03:30:58.051398438'),
 'dawn': Timestamp('2020-05-25 10:51:06.668003906'),
 'dusk': Timestamp('2020-05-26 04:18:23.730672607'),
 'nautical_dawn': Timestamp('2020-05-25 09:49:54.193455566'),
 'nautical_dusk': Timestamp('2020-05-26 05:19:36.205220703'),
 'night_end': NaT,
 'night': NaT,
 'golden_hour_end': Timestamp('2020-05-25 12:25:16.654416992'),
 'golden_hour': Timestamp('2020-05-26 02:44:13.744259521')}
```

**Comment by kylebarron** [comment]
Regardless maybe I need to catch this error
```
    return datetime.utcfromtimestamp(ms_date / 1000)
ValueError: Invalid value NaN (not a number)
```

You're welcome to try this branch: https://github.com/kylebarron/suncalc-py/tree/kyle/catch-nan

**Comment by mrputter** [comment]
Just downgraded my numpy to 1.19.1 and am still receiving the same error. (With the RuntimeWarning, which had actually occurred for me earlier as well, but I accidentally cut it from the trace.)

Wonder if it's Windows vs. Unix? I don't have a convenient Unix machine to test on at the moment.

**Comment by mrputter** [comment]
The patch fixed it! Thanks!

**Comment by kylebarron** [comment]
I pushed suncalc 0.1.2 to pypi
